
name_tool       =  "x0as"
type_tool       =  "Multi-Tools"
version_tool    =  "6.3"
coding_tool     =  "Python 3"
language_tool   =  "EN"
creator         =  "x0as??"
platform        =  "Windows 10/11 & Linux"
website         =  "nah imma do my own thing."
github_tool     =  "https://github.com/x0as"
telegram        =  "t.me/redtigersupport"
copyright       =  "Copyright (c) RedTiger 'GPL-3.0 license'"